spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/project-management"
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
